options:
  merge-default-rules: false

files:
  ignore:
    - 'src/style/theme-inspinia.scss'
    - 'src/style/theme-inspinia-mod.scss'
  include: '**/*.s(a|c)ss'

rules:
  # https://github.com/sasstools/sass-lint/tree/master/docs/rules

  ## Format
  indentation:
    - 1
    - size: 4

  final-newline: 1
  no-trailing-whitespace: 1

  ## Style
  quotes:
    - 1
    - style: single

  brace-style:
    - 1
    - style: 1tbs
      allow-sing-eline: true

  hex-notation:
    - 1
    - style: lowercase

  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-brace: 1
  space-before-colon:
    - 1
    - include: false
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1

  ## SCSS Specificities
  no-warn: 1
  no-debug: 1

  ## CSS Rules
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1

  no-misspelled-properties: 1
